//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package at.mehlox.guildwars.data.ormlite;

import java.sql.SQLException;
import android.content.Context;
import android.util.Log;
import at.mehlox.guildwars.rest.entities.base.ItemBase;
import com.j256.ormlite.android.apptools.OpenHelperManager;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class DatabaseHelper_
    extends DatabaseHelper
{

    private Context context_;
    private static DatabaseHelper_ instance_;
    private DatabaseInitializationHelper databaseInitializationHelper_;

    private DatabaseHelper_(Context context) {
        context_ = context;
    }

    public static DatabaseHelper_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new DatabaseHelper_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        databaseInitializationHelper_ = OpenHelperManager.getHelper(context_, DatabaseInitializationHelper.class);
        try {
            mItemDao = databaseInitializationHelper_.getDao(ItemBase.class);
        } catch (SQLException e) {
            Log.e("DatabaseHelper_", "Could not create DAO mItemDao", e);
        }
    }

}
