//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package at.mehlox.guildwars.rest;

import android.content.Context;

public final class RestClient_
    extends RestClient
{

    private Context context_;

    private RestClient_(Context context) {
        context_ = context;
        init_();
    }

    public static RestClient_ getInstance_(Context context) {
        return new RestClient_(context);
    }

    private void init_() {
        mRestInterface = new GuildWarsAPI_();
        afterInject();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
