//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package at.mehlox.guildwars.data;

import android.content.Context;
import at.mehlox.guildwars.rest.RestClient_;

public final class DataManager_
    extends DataManager
{

    private Context context_;

    private DataManager_(Context context) {
        context_ = context;
        init_();
    }

    public static DataManager_ getInstance_(Context context) {
        return new DataManager_(context);
    }

    private void init_() {
        mRestClient = RestClient_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
