//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package at.mehlox.guildwars.rest.java.util;

import java.util.ArrayList;
import at.mehlox.guildwars.rest.entities.MapName;

public class List_MapName
    extends ArrayList<MapName>
{


}
